spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workout?useSSL=false
    username: root
    password: deyva
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    

server.port: 8080

spring.queries.users-query : select userName, password, enabled from user where userName=?
